python -W ignore amc_fine_tune.py \
    --model=mobilenet_0.5flops \
    --dataset=imagenet \
    --lr=0.05 \
    --n_gpu=4 \
    --batch_size=1024 \
    --n_worker=22 \
    --lr_type=exp \
    --n_epoch=200 \
    --wd=4e-5 \
    --seed=2018 \
    --data_root=/mnt/imagenet/raw_jpeg/2012 \
    --ckpt_path=./checkpoints/znx_mobilenet_0.5flops_export.pth.tar
